family_dict = {
    'Jan Fallon':
        {'SO': 'Chuck Fallon',
         'Email': 'fallon.jan@gmail.com',
         'Likes': ['Birds', 'Reading', 'Candles'],
         2018: 'Gabe Fallon',
         2019: 'Jordan Fallon',
         2020: 'Katie Fallon',
         2021: 'Micah Fallon',
         2022: 'Jordan Hagan',
         2023: 'Jen Fallon'},
    'Chuck Fallon':
        {'SO': 'Jan Fallon',
         'Email': 'cpfallon77@gmail.com',
         'Likes': ['Birds', 'Running', 'Socks'],
         2018: 'Katie Fallon',
         2019: 'Jen Fallon',
         2020: 'Micah Fallon',
         2021: 'Jordan Hagan',
         2022: 'Gabe Fallon',
         2023: 'Jordan Fallon'},
    'Jordan Fallon':
        {'SO': 'Jordan Hagan',
         'Email': 'thefetts@gmail.com',
         'Likes': ['Drums', 'Video Games', 'Reading'],
         2018: 'Jen Fallon',
         2019: 'Gabe Fallon',
         2020: 'Jan Fallon',
         2021: 'Chuck Fallon',
         2022: 'Katie Fallon',
         2023: 'Micah Fallon'},
    'Gabe Fallon':
        {'SO': 'Jen Fallon',
         'Email': 'gabefallo@gmail.com',
         'Likes': ['Running', 'Music', 'Video Games'],
         2018: 'Chuck Fallon',
         2019: 'Katie Fallon',
         2020: 'Jordan Fallon',
         2021: 'Jan Fallon',
         2022: 'Micah Fallon',
         2023: 'Jordan Hagan'},
    'Micah Fallon':
        {'SO': 'Katie Fallon',
         'Email': 'reban4@gmail.com',
         'Likes': ['Video Games', 'Weed', 'Heartfelt Presents'],
         2018: 'Jordan Fallon',
         2019: 'Chuck Fallon',
         2020: 'Jordan Hagan',
         2021: 'Gabe Fallon',
         2022: 'Jen Fallon',
         2023: 'Jan Fallon'},
    'Jordan Hagan':
        {'SO': 'Jordan Fallon',
         'Email': 'Jordan.Hagan@gmail.com',
         'Likes': ['Music', 'Flowers', 'Running'],
         2018: 'Micah Fallon',
         2019: 'Jan Fallon',
         2020: 'Jen Fallon',
         2021: 'Katie Fallon',
         2022: 'Chuck Fallon',
         2023: 'Gabe Fallon'},
    'Jen Fallon':
        {'SO': 'Gabe Fallon',
         'Email': 'jennifer.a.fallo@gmail.com',
         'Likes': ['Baking', 'Running', 'Sour Beers'],
         2018: 'Jordan Hagan',
         2019: 'Micah Fallon',
         2020: 'Chuck Fallon',
         2021: 'Jordan Fallon',
         2022: 'Jan Fallon',
         2023: 'Katie Fallon'},
    'Katie Fallon':
        {'SO': 'Micah Fallon',
         'Email': 'katie.fallon.534@gmail.com',
         'Likes': ['Holistic Body Products', 'Colorado', 'Candles'],
         2018: 'Jan Fallon',
         2019: 'Jordan Hagan',
         2020: 'Gabe Fallon',
         2021: 'Jen Fallon',
         2022: 'Jordan Fallon',
         2023: 'Chuck Fallon'},
}
